version: '3'
services:
  web-app:
    build: 
      context: ./application-code/web-app/
      dockerfile: Dockerfile
    volumes:
      - ./application-code/web-app/:/var/app
      - /var/app/node_modules
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=postgres
  postgres:
    build: 
      context: ./application-code/postgres-database/
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432